INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Casa e Jardim');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza');
INSERT INTO tb_category (name) VALUES ('Automóveis');
INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Casa e Jardim');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza');
INSERT INTO tb_category (name) VALUES ('Automóveis');
INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Casa e Jardim');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza');
INSERT INTO tb_category (name) VALUES ('Automóveis');
INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Casa e Jardim');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza');
INSERT INTO tb_category (name) VALUES ('Automóveis');
INSERT INTO tb_category (name) VALUES ('Eletrônicos');
INSERT INTO tb_category (name) VALUES ('Livros');
INSERT INTO tb_category (name) VALUES ('Roupas');
INSERT INTO tb_category (name) VALUES ('Casa e Jardim');
INSERT INTO tb_category (name) VALUES ('Esportes');
INSERT INTO tb_category (name) VALUES ('Beleza');
INSERT INTO tb_category (name) VALUES ('Automóveis');